name: CI workflow
# This workflow is triggered on pushes to the repository.
on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Test
        run: |
          go test ./...
